refactor: :recycle: setup workspace to run even without `pyproject.toml` (#12)
## Description

It refactors the command to run in non-Python
projects as well, like the Quarto websites.

<!-- Please delete as appropriate: -->
This PR needs a quick review.

diff --git a/bin/spaid_setup_dev_workspace b/bin/spaid_setup_dev_workspace
--- a/bin/spaid_setup_dev_workspace
+++ b/bin/spaid_setup_dev_workspace
@@ -7,21 +7,35 @@ if [[ "$1" == "-h" ]] ; then
     echo "workspace to have any helper packages or tools installed and"
     echo "configured. These are the actions it does currently:"
     echo 
-    echo "- Installs Python package dependencies"
+    echo "- Installs Python package dependencies (if in a Poetry project)"
     echo "- Installs pre-commit hooks"
     echo "- Runs pre-commit hooks on all the files"
     echo 
     echo "This command only works if:"
     echo 
     echo "- you are in a local Git repository"
-    echo "- the repository is a Python project managed by Poetry"
     echo "- the repository has a file called '.pre-commit-config.yaml'"
     exit 0
 fi
 
-# Install dependencies just in case.
-poetry install
+precommit_file=$(pwd)/.pre-commit-config.yaml
+pyproject_file=$(pwd)/pyproject.toml
 
-# Install pre-commit hooks as defined in `.pre-commit-config.yaml`
-poetry run pre-commit install
-poetry run pre-commit run --all-files
+if [[ ! -f "$precommit_file" ]]
+then
+    echo "Error: No '$precommit_file' found. You need to create one to continue."
+    exit 1
+fi
+
+if [[ -f "$pyproject_file" ]]
+then
+    # Install dependencies just in case.
+    poetry install
+
+    # Install pre-commit hooks as defined in `.pre-commit-config.yaml`
+    poetry run pre-commit install
+    poetry run pre-commit run --all-files
+else
+    pre-commit install
+    pre-commit run --all-files
+fi
